### PR TITLE
Fix: LiveRanges removed by InlineAutoFormatEngine are not detached after removing.

### LINKED ISSUE #39: LiveRanges are not destroyed
Which is very bad for performance.

### PR DESCRIPTION
**Pull request by jodator**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: LiveRanges removed by InlineAutoFormatEngine are not detached after removing. Closes #39.

### CODE REVIEW

File: src/inlineautoformatengine.js [hunk 1]
```diff
@@ -198,6 +198,7 @@ export default class InlineAutoformatEngine {
 				// Remove delimiters.
 				for ( const range of rangesToRemove ) {
```
Comment (szymonkups) [inline src/inlineautoformatengine.js]: There are two arrays with ranges: one containing ranges to be formatted and one with ranges to be removed. You're only detaching ranges to remove. I think that we should detach `rangesToFormat` too as they're not longer needed.

Comment (jodator) [reply src/inlineautoformatengine.js]: Yep, looks like one more `LiveRange` is GC'ed:
Before (upcoming change):
selection_003

After:
selection_004

ps.: I was wondering if this shoudln't be done by Bold (and others) but as I undarstand this Bold leaves bolded range (selection) but here we're not using that range anymore - it's created only to bold text between marks.
