### PR TITLE
Fixed integration with undo

### LINKED ISSUE #53: Undo not working with inline auto format
#### Steps to reproduce
1. Type `**bold**xyz`
2. Press undo.

#### Current result
Cannot undo autoformatting.

### PR DESCRIPTION
**Pull request by szymonkups**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: Fixed integration with undo. Closes #53.

### CODE REVIEW

**Comment by Reinmar** [comment]
What's more – it's completely impossible to redo to the full text (xxxyyyzzz) on this branch. But this is something we might live with for a while.

File: src/inlineautoformatediting.js [hunk 1]
```diff
@@ -141,74 +141,75 @@ export default class InlineAutoformatEditing {
...
 		editor.model.document.on( 'change', () => {
-			const changes = editor.model.document.differ.getChanges();
+			const selection = editor.model.document.selection;
 
-			for ( const entry of changes ) {
-				if ( entry.type != 'insert' || entry.name != '$text' ) {
-					continue;
-				}
+			// Do nothing if selection is not collapsed.
+			if ( !selection.isCollapsed || !selection.focus || !selection.focus.parent ) {
```
Comment (scofalik) [inline src/inlineautoformatediting.js]: I don't recall ever checking `.focus` not to say `.focus.parent` in selection checks anywhere in the code base. Are these needed? When do they matter?

File: src/inlineautoformatediting.js [hunk 2]
```diff
@@ -141,74 +141,75 @@ export default class InlineAutoformatEditing {
...
+			// Apply format before deleting text.
+			ranges.format.forEach( range => {
+				if ( range[ 0 ] === undefined || range[ 1 ] === undefined ) {
+					return;
 				}
 
-				// Use enqueueChange to create new batch to separate typing batch from the auto-format changes.
-				editor.model.enqueueChange( writer => {
-					const validRanges = editor.model.schema.getValidRanges( rangesToFormat, attributeKey );
+				rangesToFormat.push( LiveRange.createFromParentsAndOffsets(
```
Comment (scofalik) [inline src/inlineautoformatediting.js]: Do we need to use `LiveRange`s anymore? I understand that earlier we had to use them, cause the callback was added to (something like) `applyOperation` and there might be more operations incoming and the range could change. However, now, we fire callback after all changes are done, so the ranges should not change. Additionally, we are reversing the order to prevent messing up positions. Maybe `LiveRange`s are not needed anymore.

File: src/inlineautoformatediting.js [hunk 3]
```diff
@@ -141,74 +141,75 @@ export default class InlineAutoformatEditing {
...
+			} );
 
-					// Apply format.
-					formatCallback( writer, validRanges );
+			const rangesToRemove = [];
 
-					// Detach ranges used to apply Autoformat. Prevents memory leaks. #39
-					rangesToFormat.forEach( range => range.detach() );
+			// Reverse order to not mix the offsets while removing.
+			ranges.remove.slice().reverse().forEach( range => {
```
Comment (scofalik) [inline src/inlineautoformatediting.js]: Why `.slice()` here? (I know this is not originally your code).

Comment (scofalik) [reply src/inlineautoformatediting.js]: This and above arrays transformation look alike. Maybe helper function?

File: src/inlineautoformatediting.js [hunk 4]
```diff
@@ -141,74 +141,75 @@ export default class InlineAutoformatEditing {
...
 
-				const selection = editor.model.document.selection;
+			const changes = Array.from( editor.model.document.differ.getChanges() );
+			const entry = changes[ 0 ];
 
-				if ( !selection.isCollapsed || !selection.focus || !selection.focus.parent ) {
-					continue;
-				}
+			// Typing is represented by only a single change.
+			if ( changes.length != 1 || entry.type !== 'insert' || entry.name != '$text' ) {
```
Comment (scofalik) [inline src/inlineautoformatediting.js]: Check if there was only one letter inserted (change size is `1`).

File: src/inlineautoformatediting.js (hunk 2 above)
Comment (szymonkups) [reply src/inlineautoformatediting.js]: Good call. It looks like live ranges are not needed anymore.

File: src/inlineautoformatediting.js (hunk 3 above)
Comment (szymonkups) [reply src/inlineautoformatediting.js]: >Why .slice() here? (I know this is not originally your code).

Probably to create a copy of the array since reverse() is working in place. I will try to simplify it and use a helper.
