### PR TITLE
Fixed wrong text slicing during inline autoformatting

### LINKED ISSUE #14: Can't autoformat in the middle of the text
autoformat-bug

I'd also like to be able to autoformat text just by typing `**` in two places in the content, but this can be a different issue.

### PR DESCRIPTION
**Pull request by szymonkups**
Fixes #14

### CODE REVIEW

File: tests/autoformat.js [hunk 1]
```diff
@@ -131,5 +131,14 @@ describe( 'Autoformat', () => {
 
 			expect( getData( doc ) ).to.equal( '<paragraph>foobar*[]</paragraph>' );
 		} );
+
+		it( 'should format inside the text', () => {
+			setData( doc, '<paragraph>foo **bar*[] baz</paragraph>' );
+			doc.enqueueChanges( () => {
+				batch.insert( doc.selection.getFirstPosition(), '*' );
```
Comment (Reinmar) [inline tests/autoformat.js]: Use `selection.anchor` in the future.
